export type RouteStatus = 'Cleared' | 'In Transit' | 'Customs Review' | 'Delayed' | 'Initializing'
export type TransportMode = 'Sea' | 'Air'

export const productCategories = [
  'Apparel',
  'Jewelry',
  'Home & Lifestyle',
  'Electronics',
  'Beauty',
  'F&B / Packaged',
  'Wellness',
  'Pharma',
] as const

export type ProductCategory = (typeof productCategories)[number]

export const marketFilters = [
  { code: 'AE', label: 'UAE' },
  { code: 'GB', label: 'UK' },
  { code: 'SG', label: 'SG' },
  { code: 'US', label: 'US' },
] as const

export type TradeRoute = {
  id: string
  originCode: string
  origin: string
  originPort: string
  destinationCode: string
  destination: string
  destinationPort: string
  mode: TransportMode
  cargo: string
  category: ProductCategory
  hsCode: string
  duty: string
  eta: string
  status: RouteStatus
}

export const initialRoutes: TradeRoute[] = [
  {
    id: 'XLP-40218',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Nhava Sheva',
    destinationCode: 'AE',
    destination: 'UAE',
    destinationPort: 'Jebel Ali',
    mode: 'Sea',
    cargo: 'Basmati rice · 18t',
    category: 'F&B / Packaged',
    hsCode: '1006.30',
    duty: '$1,240',
    eta: 'Oct 02',
    status: 'Cleared',
  },
  {
    id: 'XLP-40225',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Chennai',
    destinationCode: 'GB',
    destination: 'United Kingdom',
    destinationPort: 'Felixstowe',
    mode: 'Sea',
    cargo: 'Cotton apparel · 6,400 units',
    category: 'Apparel',
    hsCode: '6109.10',
    duty: '$3,882',
    eta: 'Oct 11',
    status: 'Cleared',
  },
  {
    id: 'XLP-40231',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Bengaluru (BLR)',
    destinationCode: 'SG',
    destination: 'Singapore',
    destinationPort: 'Changi',
    mode: 'Air',
    cargo: 'Pharmaceuticals · 1.2t',
    category: 'Pharma',
    hsCode: '3004.90',
    duty: '$0',
    eta: 'Sep 30',
    status: 'Cleared',
  },
  {
    id: 'XLP-40247',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Mundra',
    destinationCode: 'NL',
    destination: 'Netherlands',
    destinationPort: 'Rotterdam',
    mode: 'Sea',
    cargo: 'Cosmetics & skincare · 8t',
    category: 'Beauty',
    hsCode: '3304.99',
    duty: '$5,610',
    eta: 'Oct 18',
    status: 'In Transit',
  },
  {
    id: 'XLP-40252',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Delhi (DEL)',
    destinationCode: 'US',
    destination: 'United States',
    destinationPort: 'JFK, New York',
    mode: 'Air',
    cargo: 'Handcrafted textiles · 900kg',
    category: 'Home & Lifestyle',
    hsCode: '6304.91',
    duty: '$2,145',
    eta: 'Oct 03',
    status: 'Customs Review',
  },
  {
    id: 'XLP-40266',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Kolkata',
    destinationCode: 'DE',
    destination: 'Germany',
    destinationPort: 'Hamburg',
    mode: 'Sea',
    cargo: 'Leather goods · 9t',
    category: 'Apparel',
    hsCode: '4202.21',
    duty: '$4,020',
    eta: 'Oct 21',
    status: 'Delayed',
  },
  {
    id: 'XLP-40271',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Kochi',
    destinationCode: 'AE',
    destination: 'UAE',
    destinationPort: 'Khalifa Port',
    mode: 'Sea',
    cargo: 'Spices & tea · 11t',
    category: 'F&B / Packaged',
    hsCode: '0910.99',
    duty: '$690',
    eta: 'Oct 05',
    status: 'Cleared',
  },
  {
    id: 'XLP-40274',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Mumbai (BOM)',
    destinationCode: 'AE',
    destination: 'UAE',
    destinationPort: 'Dubai (DXB)',
    mode: 'Air',
    cargo: 'Diamond jewellery · 85kg',
    category: 'Jewelry',
    hsCode: '7113.19',
    duty: '$6,120',
    eta: 'Oct 01',
    status: 'Customs Review',
  },
  {
    id: 'XLP-40279',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Delhi (DEL)',
    destinationCode: 'GB',
    destination: 'United Kingdom',
    destinationPort: 'Heathrow (LHR)',
    mode: 'Air',
    cargo: 'Ayurvedic skincare · 1.8t',
    category: 'Beauty',
    hsCode: '3304.99',
    duty: '$1,460',
    eta: 'Oct 06',
    status: 'In Transit',
  },
  {
    id: 'XLP-40283',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Chennai',
    destinationCode: 'SG',
    destination: 'Singapore',
    destinationPort: 'Pasir Panjang',
    mode: 'Sea',
    cargo: 'Consumer electronics · 14t',
    category: 'Electronics',
    hsCode: '8517.62',
    duty: '$0',
    eta: 'Oct 09',
    status: 'Cleared',
  },
  {
    id: 'XLP-40288',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Nhava Sheva',
    destinationCode: 'US',
    destination: 'United States',
    destinationPort: 'Newark',
    mode: 'Sea',
    cargo: 'Herbal supplements · 7t',
    category: 'Wellness',
    hsCode: '2106.90',
    duty: '$1,980',
    eta: 'Oct 27',
    status: 'Delayed',
  },
  {
    id: 'XLP-40292',
    originCode: 'IN',
    origin: 'India',
    originPort: 'Jaipur (JAI)',
    destinationCode: 'SG',
    destination: 'Singapore',
    destinationPort: 'Changi',
    mode: 'Air',
    cargo: 'Silver jewellery · 60kg',
    category: 'Jewelry',
    hsCode: '7113.11',
    duty: '$0',
    eta: 'Oct 03',
    status: 'Cleared',
  },
]

const newRouteTemplates: Omit<TradeRoute, 'id' | 'status'>[] = [
  {
    originCode: 'IN',
    origin: 'India',
    originPort: 'Hyderabad (HYD)',
    destinationCode: 'SG',
    destination: 'Singapore',
    destinationPort: 'Changi',
    mode: 'Air',
    cargo: 'Electronics · 2.4t',
    category: 'Electronics',
    hsCode: '8542.31',
    duty: '$0',
    eta: 'Oct 04',
  },
  {
    originCode: 'IN',
    origin: 'India',
    originPort: 'Tuticorin',
    destinationCode: 'GB',
    destination: 'United Kingdom',
    destinationPort: 'Southampton',
    mode: 'Sea',
    cargo: 'Ceramic tiles · 20t',
    category: 'Home & Lifestyle',
    hsCode: '6907.21',
    duty: '$2,310',
    eta: 'Oct 24',
  },
  {
    originCode: 'IN',
    origin: 'India',
    originPort: 'Mumbai (BOM)',
    destinationCode: 'AE',
    destination: 'UAE',
    destinationPort: 'Dubai (DXB)',
    mode: 'Air',
    cargo: 'Gold jewellery · 140kg',
    category: 'Jewelry',
    hsCode: '7113.19',
    duty: '$8,450',
    eta: 'Sep 29',
  },
]

export function createRoute(sequence: number): TradeRoute {
  const template = newRouteTemplates[sequence % newRouteTemplates.length]
  return {
    ...template,
    id: `XLP-${40280 + sequence * 7}`,
    status: 'Initializing',
  }
}
